version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quiz_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz_network

  app:
    build: .
    container_name: quiz_app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      GIN_MODE: ${GIN_MODE}
      ENV: ${ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      API_TOKEN: ${API_TOKEN}
      URL: ${URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quiz_network

volumes:
  postgres_data:

networks:
  quiz_network:
    driver: bridge
