version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quiz_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz_network

  redis:
    image: redis:alpine
    container_name: quiz_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - quiz_network

  app:
    build: .
    container_name: quiz_app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      APP_NAME: ${APP_NAME}
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      GIN_MODE: ${GIN_MODE}
      ENV: ${ENV}
      LOG_LEVEL: ${LOG_LEVEL}
      API_TOKEN: ${API_TOKEN}
      URL: ${URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_SESSION_TTL: ${REDIS_SESSION_TTL}
      QUESTIONS_LIMIT: ${QUESTIONS_LIMIT}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      STATIC_DIR: ${STATIC_DIR}
      FRONTEND_DIR: ${FRONTEND_DIR}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - quiz_network

volumes:
  postgres_data:
  redis_data:

networks:
  quiz_network:
    driver: bridge
